services:
  python:
    build: .
    container_name: data_engineer_python
    environment:
      PGUSER: vfuster
      PGPASSWORD: Bonjour42
      PGDATABASE: piscineds
      PGHOST: ${PGHOST}
      PGPORT: 5433
    stdin_open: true
    tty: true
